apiVersion: v1
kind: Service
metadata:
  name: realfood-payments-service
spec:
  type: ClusterIP
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: realfood-payments-app