kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv
spec:
  storageClassName: rabbitmq-sc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /rabbitmq-data