apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realfood-rabbitmq-pv-claim
  labels:
    app: realfood-rabbitmq
spec:
  storageClassName: "realfood-rabbitmq-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi