kind: PersistentVolume
apiVersion: v1
metadata:
  name: realfood-rabbitmq-pv
spec:
  storageClassName: realfood-rabbitmq-sc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /realfood-rabbitmq-data