apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqldbpayments
  name: sqldbpayments
spec:
  type: ClusterIP
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: sqldbpayments
