name: Main workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Java application and run test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run unitary test
      run: mvn -B -Dtest="es/urjc/realfood/payments/unit/*" -DfailIfNoTests=false test
    - name: Run integration test
      run: mvn -B -Dtest="es/urjc/realfood/payments/integration/*" -DfailIfNoTests=false test